### ISSUE TITLE
how do we use GitHub for project management?

### ISSUE THREAD

**Issue by KatieOC** [ICPI/HEI-Dashboard#3]
Help! @shapaklyak and @aliyahwakil 

we don't know where to store our 1st meeting notes for the EID dashboard? :)

**Comment by shapaklyak** [comment]
@KatieOC , DIV stores notes in a Wiki page under its repository. You could do the same for here and name the page EID Dashboard Notes.

**Comment by KatieOC** [comment]
@shapaklyak our automation isn't working :( @aliyahwakil

**Comment by shapaklyak** [comment]
oh no.. i'll help you out w/it at 5 if you'd like...

**Comment by KatieOC** [comment]
moved meeting notes to wiki page. closing this issue.
