### ISSUE TITLE
Link to Draft Dashboard on PEPFAR.net

### ISSUE THREAD

**Issue by nmcdavid** [ICPI/HEI-Dashboard#7]
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Working%20Folder/DRAFT%20PMTCT_EID_HEI%20Dashboard%20-%2007.11.2018.xlsx

**Comment by KatieOC** [comment]
@megitoh here is the link to the dashboard

**Comment by megitoh** [comment]
Sorry Katie, but I keep getting directed to an “Accessed required” page on Pepfar.net.
